language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
    - pip install scipy
script:
    - python -m pytest ./tests/test.py --cov=./
after_success:
    - codecov

# test codecov
